# Generated by Django 2.1.2 on 2018-10-14 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20181013_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislikeanswer',
            name='dislike_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ans_dislikes', to='qa.Answer'),
        ),
        migrations.AlterField(
            model_name='likeanswer',
            name='like_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ans_likes', to='qa.Answer'),
        ),
    ]
